import type { CircuitTrack } from "./types"

export const CIRCUIT_TRACKS: CircuitTrack[] = [
  {
    id: "networking",
    label: "Networking",
    accentColor: "#60a5fa",
    nodes: [
      {
        id: "n0",
        label: "Fundamentals",
        sub: "Network Basics",
        type: "start",
        col: 0,
        row: 0,
        desc: "OSI Model, TCP/IP stack, binary & subnetting dasar yang wajib dikuasai.",
        tags: ["OSI", "TCP/IP", "Binary"],
      },
      {
        id: "n1",
        label: "IP & Routing",
        sub: "Addressing",
        type: "module",
        col: 1,
        row: 0,
        desc: "IPv4/IPv6, subnetting, static & dynamic routing (OSPF, BGP).",
        tags: ["IPv4", "IPv6", "OSPF"],
      },
      {
        id: "n2",
        label: "Switching",
        sub: "VLAN & STP",
        type: "module",
        col: 2,
        row: 0,
        desc: "VLAN segmentation, trunk ports, STP, EtherChannel.",
        tags: ["VLAN", "STP", "Layer 2"],
      },
      {
        id: "n3",
        label: "MikroTik",
        sub: "RouterOS Lab",
        type: "project",
        col: 2,
        row: 1,
        desc: "Hands-on lab konfigurasi MikroTik: firewall, hotspot, VPN.",
        tags: ["RouterOS", "Firewall", "VPN"],
      },
      {
        id: "n4",
        label: "Network Sec",
        sub: "Defense & Attack",
        type: "module",
        col: 1,
        row: 1,
        desc: "Packet sniffing dengan Wireshark, IDS/IPS, network hardening.",
        tags: ["Wireshark", "IDS", "Hardening"],
      },
      {
        id: "n5",
        label: "Monitoring",
        sub: "SNMP & Logs",
        type: "module",
        col: 0,
        row: 1,
        desc: "Monitoring jaringan dengan SNMP, syslog, dan Grafana stack.",
        tags: ["SNMP", "Grafana", "Syslog"],
      },
      {
        id: "n6",
        label: "Cloud Net",
        sub: "AWS VPC",
        type: "module",
        col: 0,
        row: 2,
        desc: "VPC design, subnets, security groups, peering, Transit Gateway.",
        tags: ["VPC", "AWS", "Transit GW"],
      },
      {
        id: "n7",
        label: "SD-WAN",
        sub: "Modern Infra",
        type: "module",
        col: 1,
        row: 2,
        desc: "Software-defined networking, overlay networks, dan automation.",
        tags: ["SDN", "Overlay", "Automation"],
      },
      {
        id: "n8",
        label: "CAPSTONE",
        sub: "Final Project",
        type: "cap",
        col: 2,
        row: 2,
        desc: "Bangun enterprise network end-to-end: design, deploy, monitor, secure.",
        tags: ["Enterprise", "Full Deploy", "Pentest"],
      },
    ],
    connections: [
      ["n0", "n1"],
      ["n1", "n2"],
      ["n2", "n3"],
      ["n3", "n4"],
      ["n4", "n5"],
      ["n5", "n6"],
      ["n6", "n7"],
      ["n7", "n8"],
    ],
  },
  {
    id: "devsecops",
    label: "DevSecOps",
    accentColor: "#c084fc",
    nodes: [
      {
        id: "d0",
        label: "Linux & Shell",
        sub: "OS Fundamentals",
        type: "start",
        col: 0,
        row: 0,
        desc: "Linux filesystem, shell scripting bash, process & user management.",
        tags: ["Linux", "Bash", "Systemd"],
      },
      {
        id: "d1",
        label: "Docker",
        sub: "Containerization",
        type: "module",
        col: 1,
        row: 0,
        desc: "Docker image, container lifecycle, volumes, compose, registry.",
        tags: ["Docker", "Compose", "Registry"],
      },
      {
        id: "d2",
        label: "Kubernetes",
        sub: "Orchestration",
        type: "module",
        col: 2,
        row: 0,
        desc: "Pods, deployments, services, ingress, HPA, namespaces.",
        tags: ["K8s", "Helm", "Ingress"],
      },
      {
        id: "d3",
        label: "CI/CD",
        sub: "GitLab / GitHub",
        type: "project",
        col: 2,
        row: 1,
        desc: "Pipeline automation: build, test, scan, deploy — GitLab CI & GitHub Actions.",
        tags: ["GitLab CI", "Actions", "Pipelines"],
      },
      {
        id: "d4",
        label: "Security Scan",
        sub: "SAST / DAST",
        type: "module",
        col: 1,
        row: 1,
        desc: "Static & dynamic analysis, dependency audit, Trivy, Snyk.",
        tags: ["Trivy", "Snyk", "OWASP"],
      },
      {
        id: "d5",
        label: "Vault",
        sub: "Secrets Mgmt",
        type: "module",
        col: 0,
        row: 1,
        desc: "HashiCorp Vault: secret engines, policies, dynamic credentials.",
        tags: ["Vault", "PKI", "Secrets"],
      },
      {
        id: "d6",
        label: "Terraform",
        sub: "IaC",
        type: "module",
        col: 0,
        row: 2,
        desc: "Infrastructure as Code: providers, state, modules, workspaces.",
        tags: ["Terraform", "IaC", "State"],
      },
      {
        id: "d7",
        label: "Observability",
        sub: "Grafana Stack",
        type: "module",
        col: 1,
        row: 2,
        desc: "Prometheus, Loki, Grafana: metrics, logs, alerting, dashboards.",
        tags: ["Prometheus", "Loki", "Grafana"],
      },
      {
        id: "d8",
        label: "CAPSTONE",
        sub: "Final Project",
        type: "cap",
        col: 2,
        row: 2,
        desc: "Deploy secure app end-to-end: IaC → K8s → pipeline → monitoring → pentest.",
        tags: ["K8s", "Secure SDLC", "Full Stack"],
      },
    ],
    connections: [
      ["d0", "d1"],
      ["d1", "d2"],
      ["d2", "d3"],
      ["d3", "d4"],
      ["d4", "d5"],
      ["d5", "d6"],
      ["d6", "d7"],
      ["d7", "d8"],
    ],
  },
  {
    id: "programming",
    label: "Programming",
    accentColor: "#29E68C",
    nodes: [
      {
        id: "p0",
        label: "Git & CLI",
        sub: "Version Control",
        type: "start",
        col: 0,
        row: 0,
        desc: "Git workflow, branching strategy, PR review, conventional commits.",
        tags: ["Git", "GitHub", "Commits"],
      },
      {
        id: "p1",
        label: "Python",
        sub: "Backend Language",
        type: "module",
        col: 1,
        row: 0,
        desc: "Python fundamentals, OOP, async programming, data structures.",
        tags: ["Python", "OOP", "Async"],
      },
      {
        id: "p2",
        label: "REST API",
        sub: "FastAPI / Express",
        type: "module",
        col: 2,
        row: 0,
        desc: "API design, HTTP methods, auth (JWT/OAuth), rate limiting, docs.",
        tags: ["FastAPI", "REST", "JWT"],
      },
      {
        id: "p3",
        label: "Database",
        sub: "SQL & NoSQL",
        type: "project",
        col: 2,
        row: 1,
        desc: "PostgreSQL schema design, indexing, query optimization, Redis.",
        tags: ["PostgreSQL", "Redis", "Indexing"],
      },
      {
        id: "p4",
        label: "React",
        sub: "Frontend",
        type: "module",
        col: 1,
        row: 1,
        desc: "Component patterns, hooks, state management, Tailwind, Vite.",
        tags: ["React", "Hooks", "Tailwind"],
      },
      {
        id: "p5",
        label: "Testing",
        sub: "QA & Automation",
        type: "module",
        col: 0,
        row: 1,
        desc: "Unit, integration, E2E testing: pytest, Vitest, Playwright.",
        tags: ["Pytest", "Vitest", "E2E"],
      },
      {
        id: "p6",
        label: "Auth & Security",
        sub: "App Security",
        type: "module",
        col: 0,
        row: 2,
        desc: "OWASP Top 10, input validation, CSRF, XSS, secure headers.",
        tags: ["OWASP", "Auth", "Headers"],
      },
      {
        id: "p7",
        label: "Deploy",
        sub: "Cloud & Containers",
        type: "module",
        col: 1,
        row: 2,
        desc: "Dockerize app, deploy ke VPS/cloud, reverse proxy Nginx, SSL.",
        tags: ["Docker", "Nginx", "SSL"],
      },
      {
        id: "p8",
        label: "CAPSTONE",
        sub: "Final Project",
        type: "cap",
        col: 2,
        row: 2,
        desc: "Bangun full-stack production app: API + frontend + database + deploy + CI/CD.",
        tags: ["Full-Stack", "Production", "CI/CD"],
      },
    ],
    connections: [
      ["p0", "p1"],
      ["p1", "p2"],
      ["p2", "p3"],
      ["p3", "p4"],
      ["p4", "p5"],
      ["p5", "p6"],
      ["p6", "p7"],
      ["p7", "p8"],
    ],
  },
]
