name: Test Deploy ITTS Community

on:
  push:
    branches:
      - dev

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Deploy with Docker Compose
        run: |
          pwd
          ls -lah
          docker compose down || true
          docker compose up -d --build